### ISSUE TITLE
Dialog customization when using ColorPickerButton

### ISSUE THREAD

**Issue by Xjph** [egorozh/Egorozh.ColorPicker.WPF#17]
Is there any ability currently to customize the dialog when using the button? For example, removing window decorations and title bar. A quick read of the source leads me to believe there is not.

Is this something that you might consider adding to the project?

**Comment by egorozh** [comment]
Moved the color button into a common class, as done in a WPF project. 
Now you can create your own button and override the ChangeColor method to customize the dialog.
``` cs 
internal class CustomColorPickerButton : ColorPickerButtonBase
    {
        protected override async Task ChangeColor()
        {
            ColorPickerDialog dialog = new()
            {
                Color = Color,
                Colors = Colors,
                ExtendClientAreaToDecorationsHint = false,
                SystemDecorations = SystemDecorations.None,
                Title = "Custom Title"
            };

            var res = await dialog.ShowDialog<bool>(Owner);

            if (res)
                Color = dialog.Color;
        }
    }
```
