### ISSUE TITLE
Using any Themes spoils ListBoxItem default style

### ISSUE THREAD

**Issue by joeuge** [egorozh/Egorozh.ColorPicker.WPF#19]
Using any Themes spoils ListBoxItem style
<Application.Styles>
  <egorozh:FluentTheme/>

This is because of
ColorPalette.axaml overrides ListBoxItem style
<Style Selector="ListBoxItem">

**Comment by egorozh** [comment]
I made a quick fix in version 11.0.1. 
Please check and if everything is ok, close the issue))

**Comment by joeuge** [comment]
perfect!
