### ISSUE TITLE
ColorPickerDialog.Color isn't work as init value

### ISSUE THREAD

**Issue by joeuge** [egorozh/Egorozh.ColorPicker.WPF#20]
ColorPickerDialog dialog = new()
{
  Color = Colors.Aqua // has no effect
};
dialog.Show(mainWindow);

**Comment by egorozh** [comment]
Thank you for report.

I fixed this in the new version 11.0.2. Could you check it out? If everything is ok, then close the issue)

**Comment by joeuge** [comment]
Uups! I've taken 11.0.2 from nuget.org, but nothing changed.
ColorPickerDialog.Color isn't work as init value

**Comment by joeuge** [comment]
nuget.org, package version 11.0.2
There are old dll's there (11.0.1 of 27/01/2024)

**Comment by egorozh** [comment]
Strange. I'll watch it again this evening

**Comment by egorozh** [comment]
Rebuilt the package. Try version 11.0.3

... for some reason, 11.0.2 did not include edits when packaging the library

**Comment by joeuge** [comment]
Thanks
